/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityAgentContext = {
  _id: string;
  _type: "sanity.agentContext";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  groqFilter?: string;
  instructions?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type VideoChunk = {
  _type: "videoChunk";
  startSeconds?: number;
  text?: string;
};

export type VideoChapter = {
  _type: "videoChapter";
  startSeconds?: number;
  label?: string;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  url?: string;
  title?: string;
  chapters?: Array<
    {
      _key: string;
    } & VideoChapter
  >;
  chunks?: Array<
    {
      _key: string;
    } & VideoChunk
  >;
};

export type LessonResource = {
  _type: "lessonResource";
  type?:
    | "documentation"
    | "guide"
    | "repository"
    | "article"
    | "video"
    | "tool"
    | "other";
  title?: string;
  description?: string;
  url?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?:
    | "layers"
    | "database"
    | "gauge"
    | "cloud"
    | "code"
    | "rocket"
    | "shield"
    | "zap";
  title?: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title?: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  videoUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  duration?: number;
  keyPoints?: Array<string>;
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & LessonResource
  >;
  isFreePreview?: boolean;
  studentCount?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level?: "beginner" | "intermediate" | "advanced";
  price?: number;
  isPopular?: boolean;
  studentCount?: number;
  instructor?: InstructorReference;
  category?: CategoryReference;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityAgentContext
  | Slug
  | VideoChunk
  | VideoChapter
  | Video
  | LessonResource
  | LearningOutcome
  | LessonReference
  | Module
  | SanityImageAssetReference
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/lib/queries.ts
// Variable: CATALOG_COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(title asc) {    _id,    _type,    title,    "slug": slug.current,    summary,    level,    studentCount,    coverImage {      ...,      asset->{_id, url, metadata{dimensions, lqip}}    },    "category": category->{_id, title, "slug": slug.current},    "instructor": instructor->{_id, name, "slug": slug.current},    "moduleCount": count(modules),    "lessonDurations": modules[].lessons[]->duration  }
export type CATALOG_COURSES_QUERY_RESULT = Array<{
  _id: string;
  _type: "course";
  title: string | null;
  slug: string | null;
  summary: string | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  studentCount: number | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
  } | null;
  moduleCount: number | null;
  lessonDurations: Array<number | null> | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)][]{"slug": slug.current}
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_DETAIL_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {    _id,    _type,    title,    "slug": slug.current,    summary,    level,    price,    isPopular,    studentCount,    coverImage {      ...,      asset->{_id, url, metadata{dimensions, lqip}}    },    learningOutcomes[]{"_key": _key, icon, title, description},    "category": category->{_id, title, "slug": slug.current, description},    "instructor": instructor->{_id, name, "slug": slug.current, expertise},    modules[]{      _key,      title,      summary,      "lessons": lessons[]->{        _id,        title,        "slug": slug.current,        summary,        duration,        isFreePreview,        studentCount      }    }  }
export type COURSE_DETAIL_QUERY_RESULT = {
  _id: string;
  _type: "course";
  title: string | null;
  slug: string | null;
  summary: string | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  isPopular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  learningOutcomes: Array<{
    _key: string;
    icon:
      | "cloud"
      | "code"
      | "database"
      | "gauge"
      | "layers"
      | "rocket"
      | "shield"
      | "zap"
      | null;
    title: string | null;
    description: string | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
    description: string | null;
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
    expertise: Array<string> | null;
  } | null;
  modules: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      summary: string | null;
      duration: number | null;
      isFreePreview: boolean | null;
      studentCount: number | null;
    }> | null;
  }> | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_DETAIL_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    _type,    title,    "slug": slug.current,    summary,    videoUrl,    poster {      ...,      asset->{_id, url, metadata{dimensions, lqip}}    },    duration,    isFreePreview,    studentCount,    keyPoints,    notes,    proTip,    resources[]{"_key": _key, type, title, description, url},    "course": *[_type == "course" && references(^._id)][0] {      _id,      title,      "slug": slug.current,      coverImage {        ...,        asset->{_id, url, metadata{dimensions, lqip}}      },      studentCount,      level,      "category": category->{_id, title, "slug": slug.current},      "instructor": instructor->{_id, name, "slug": slug.current, photo},      modules[]{        _key,        title,        "lessons": lessons[]->{_id, title, "slug": slug.current, duration, isFreePreview}      }    }  }
export type LESSON_DETAIL_QUERY_RESULT = {
  _id: string;
  _type: "lesson";
  title: string | null;
  slug: string | null;
  summary: string | null;
  videoUrl: string | null;
  poster: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  duration: number | null;
  isFreePreview: boolean | null;
  studentCount: number | null;
  keyPoints: Array<string> | null;
  notes: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type:
      | "article"
      | "documentation"
      | "guide"
      | "other"
      | "repository"
      | "tool"
      | "video"
      | null;
    title: string | null;
    description: string | null;
    url: string | null;
  }> | null;
  course: {
    _id: string;
    title: string | null;
    slug: string | null;
    coverImage: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    studentCount: number | null;
    level: "advanced" | "beginner" | "intermediate" | null;
    category: {
      _id: string;
      title: string | null;
      slug: string | null;
    } | null;
    instructor: {
      _id: string;
      name: string | null;
      slug: string | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    } | null;
    modules: Array<{
      _key: string;
      title: string | null;
      lessons: Array<{
        _id: string;
        title: string | null;
        slug: string | null;
        duration: number | null;
        isFreePreview: boolean | null;
      }> | null;
    }> | null;
  } | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTOR_DETAIL_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    _type,    name,    "slug": slug.current,    expertise,    bio,    photo {      ...,      asset->{_id, url, metadata{dimensions, lqip}}    },    "courses": *[_type == "course" && references(^._id)] | order(title asc) {      _id,      title,      "slug": slug.current,      summary,      level,      coverImage {        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    }  }
export type INSTRUCTOR_DETAIL_QUERY_RESULT = {
  _id: string;
  _type: "instructor";
  name: string | null;
  slug: string | null;
  expertise: Array<string> | null;
  bio: string | null;
  photo: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    level: "advanced" | "beginner" | "intermediate" | null;
    coverImage: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }>;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    description  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: AGENT_CONTEXT_QUERY
// Query: *[_type == "sanity.agentContext" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    groqFilter,    instructions  }
export type AGENT_CONTEXT_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  groqFilter: string | null;
  instructions: string | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: SEARCH_HYDRATE_QUERY
// Query: *[_type == "lesson" && _id in $ids]{    _id,    _createdAt,    title,    "slug": slug.current,    summary,    duration,    keyPoints,    "course": *[_type == "course" && references(^._id)][0]{      _id,      title,      "slug": slug.current,      "category": category->{_id, title, "slug": slug.current},      modules[]{        _key,        title,        "lessons": lessons[]->{_id}      }    }  }
export type SEARCH_HYDRATE_QUERY_RESULT = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  duration: number | null;
  keyPoints: Array<string> | null;
  course: {
    _id: string;
    title: string | null;
    slug: string | null;
    category: {
      _id: string;
      title: string | null;
      slug: string | null;
    } | null;
    modules: Array<{
      _key: string;
      title: string | null;
      lessons: Array<{
        _id: string;
      }> | null;
    }> | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course" && defined(slug.current)] | order(title asc) {\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    summary,\n    level,\n    studentCount,\n    coverImage {\n      ...,\n      asset->{_id, url, metadata{dimensions, lqip}}\n    },\n    "category": category->{_id, title, "slug": slug.current},\n    "instructor": instructor->{_id, name, "slug": slug.current},\n    "moduleCount": count(modules),\n    "lessonDurations": modules[].lessons[]->duration\n  }\n': CATALOG_COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)][]{"slug": slug.current}\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    summary,\n    level,\n    price,\n    isPopular,\n    studentCount,\n    coverImage {\n      ...,\n      asset->{_id, url, metadata{dimensions, lqip}}\n    },\n    learningOutcomes[]{"_key": _key, icon, title, description},\n    "category": category->{_id, title, "slug": slug.current, description},\n    "instructor": instructor->{_id, name, "slug": slug.current, expertise},\n    modules[]{\n      _key,\n      title,\n      summary,\n      "lessons": lessons[]->{\n        _id,\n        title,\n        "slug": slug.current,\n        summary,\n        duration,\n        isFreePreview,\n        studentCount\n      }\n    }\n  }\n': COURSE_DETAIL_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    summary,\n    videoUrl,\n    poster {\n      ...,\n      asset->{_id, url, metadata{dimensions, lqip}}\n    },\n    duration,\n    isFreePreview,\n    studentCount,\n    keyPoints,\n    notes,\n    proTip,\n    resources[]{"_key": _key, type, title, description, url},\n    "course": *[_type == "course" && references(^._id)][0] {\n      _id,\n      title,\n      "slug": slug.current,\n      coverImage {\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      },\n      studentCount,\n      level,\n      "category": category->{_id, title, "slug": slug.current},\n      "instructor": instructor->{_id, name, "slug": slug.current, photo},\n      modules[]{\n        _key,\n        title,\n        "lessons": lessons[]->{_id, title, "slug": slug.current, duration, isFreePreview}\n      }\n    }\n  }\n': LESSON_DETAIL_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    _id,\n    _type,\n    name,\n    "slug": slug.current,\n    expertise,\n    bio,\n    photo {\n      ...,\n      asset->{_id, url, metadata{dimensions, lqip}}\n    },\n    "courses": *[_type == "course" && references(^._id)] | order(title asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      summary,\n      level,\n      coverImage {\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    }\n  }\n': INSTRUCTOR_DETAIL_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "sanity.agentContext" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    groqFilter,\n    instructions\n  }\n': AGENT_CONTEXT_QUERY_RESULT;
    '\n  *[_type == "lesson" && _id in $ids]{\n    _id,\n    _createdAt,\n    title,\n    "slug": slug.current,\n    summary,\n    duration,\n    keyPoints,\n    "course": *[_type == "course" && references(^._id)][0]{\n      _id,\n      title,\n      "slug": slug.current,\n      "category": category->{_id, title, "slug": slug.current},\n      modules[]{\n        _key,\n        title,\n        "lessons": lessons[]->{_id}\n      }\n    }\n  }\n': SEARCH_HYDRATE_QUERY_RESULT;
  }
}
