import { defineArrayMember, defineField, defineType } from 'sanity'
import { VideoIcon } from '@sanity/icons'

/**
 * The internal lookup behind a video result.
 *
 * One document per unique video URL, not per lesson, so three lessons sharing a video share one
 * transcript. The pipeline derives the id from the URL, so re-running ingestion replaces these
 * documents instead of creating new ones.
 *
 * Every field is read-only because the offline pipeline owns all of it. A hand edit here is lost
 * on the next run, which is why the Studio labels these documents as generated.
 *
 * There is deliberately no field holding the whole transcript. AGENTS.md section 12 warns that
 * returning one to the model overflows the context window, so the transcript only ever exists as
 * many short `chunks`, each queryable on its own. Search matches `chapters` first and falls back
 * to `chunks`.
 */
export const video = defineType({
  name: 'video',
  title: 'Video',
  type: 'document',
  icon: VideoIcon,
  description:
    'Generated by the offline ingestion pipeline. Holds the table of contents and the timestamped transcript for one video. Never shown as a result on its own; search ties a matched moment to the lesson that uses this video.',
  groups: [
    { name: 'source', title: 'Source', default: true },
    { name: 'chapters', title: 'Chapters' },
    { name: 'chunks', title: 'Transcript' },
  ],
  fields: [
    defineField({
      name: 'id',
      title: 'Video ID',
      type: 'string',
      group: 'source',
      description: 'Provider id derived from the video URL. Also the document key after "video.".',
      readOnly: true,
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: 'url',
      title: 'Video URL',
      type: 'url',
      group: 'source',
      description: 'Canonical watch URL. Lessons point at the same video with their own videoUrl.',
      readOnly: true,
      validation: (rule) =>
        rule.required().uri({ scheme: ['http', 'https'] }).error('Must be an http or https URL'),
    }),
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'source',
      description: 'The title the provider reports. Shown in the Studio list only.',
      readOnly: true,
      validation: (rule) => rule.max(200),
    }),
    defineField({
      name: 'chapters',
      title: 'Chapters',
      type: 'array',
      group: 'chapters',
      description:
        'Table of contents, ordered by startSeconds. Search resolves a timestamp against these first because the labels are clean. Empty when the source has no chapter markers, in which case search matches the transcript instead.',
      readOnly: true,
      of: [defineArrayMember({ type: 'videoChapter' })],
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: 'chunks',
      title: 'Transcript chunks',
      type: 'array',
      group: 'chunks',
      description:
        'The transcript as short timestamped pieces, ordered by startSeconds. No field holds the whole transcript.',
      readOnly: true,
      of: [defineArrayMember({ type: 'videoChunk' })],
      validation: (rule) => rule.unique(),
    }),
  ],
  preview: {
    select: {
      title: 'title',
      id: 'id',
      chapters: 'chapters',
      chunks: 'chunks',
    },
    prepare({ title, id, chapters, chunks }) {
      const chapterCount = Array.isArray(chapters) ? chapters.length : 0
      const chunkCount = Array.isArray(chunks) ? chunks.length : 0

      return {
        title: title || id || 'Video',
        subtitle: `${chapterCount} chapters, ${chunkCount} transcript chunks`,
      }
    },
  },
})
